### ISSUE TITLE
86Box VM with a MO (Magneto-Optical) drive crashes the installer

### ISSUE THREAD

**Issue by SoftwareGuy** [oerg866/win98-quickinstall#17]
The chances of people having a MO (Magneto-Optical) drive would probably be pretty slim, but in 86Box if you try to add one that doesn't have any medium inserted into it and run the installer, when it gets to the CFDisk part, it'll crash with a Guru Meditation about it being unable to determine the hard disk type.

![Monitor_1_20241107-233845-174](https://github.com/user-attachments/assets/c151e36a-f49e-45de-a500-51b19459108e)

Might be very much a edge usage case, but worth bullet-proofing?

**Comment by oerg866** [comment]
Eh???? Okay that is weird :D 

Can you post the output of the command `lsblk -I 8,3 -n -b -p -P -oTYPE,KNAME,PARTTYPE,SIZE,MIN-IO,OPT-IO,MODEL`?
