### ISSUE TITLE
Looking for Generic Modem Drivers

### ISSUE THREAD

**Issue by jzanecook** [oerg866/win98-quickinstall#18]
## Context

I've been pimping up my old 1998 Toshiba Satellite laptop for fun. I've gotten an SD card to 2.5" IDE adapter and I'm using libvirt to setup and install everything onto a VM then save that to the SD card for the machine to boot. This has worked magnificently, especially with this quickinstall which is great. Huge props.

One of the things I've wanted to do through this was follow [this guide for setting up a Raspberry Pi as a modem](https://www.steptail.com/guides:virtual_modem), which I've gotten up and running to the point that I can use hyperterm to communicate ([end of section 4](https://www.steptail.com/guides:virtual_modem:section_4)). My issue is on one of the next steps, for ["connecting windows 9x to the internet"](https://www.steptail.com/guides:connecting_windows_9x_to_the_internet).

## Problem
The guide recommends adding a generic modem driver just called "Standard 28800 bps Modem", but with this installation I only see "Accton Technology Corporation" and "IBM" in the Manufacturer list rather than the "(Standard Modem Types)" listing shown in the below referenced screenshot.

![image from the guide](https://www.steptail.com/_media/guides:pics:win95-modem-setup-5.png)

I've scoured through the drivers trying to find what could be this one, but my understanding is limited on where to find these things. I'm sure it would be different if it were a regular device. Any idea where I could find and add this generic driver?

Thanks for the help and for the good work on this repo.

**Comment by jzanecook** [comment]
@oerg866,

I also just went on vacation :D 

A week on a cruise to Mexico/Honduras for thanksgiving. Was a good time.

How are you doing?

**Comment by oerg866** [comment]
Not well. I got the flu while traveling and now i'm in bed for a few days :( Don't worry, I haven't forgotten about this :)

**Comment by jzanecook** [comment]
That blows. Get well soon!

**Comment by jzanecook** [comment]
Found it!

mdmgen.inf was located in the Net*.cab packages

Took a bit of digging (and a few tries writing my own based on some null modem drivers I'd seen before) but nothing worked until I finally got the generic ones.

I now can not only login to my raspberry pi from hyperterm, but I can also now surf the world wide web. :+1:

**Comment by oerg866** [comment]
Yes that was along my line of thinking, I will modify the preparation
script to include the generic modem driver INF file but still get rid of
all the others, that way basic modem functionality remains in the built
packages
