### ISSUE TITLE
Adding cregfix.com

### ISSUE THREAD

**Issue by Glinckey** [oerg866/win98-quickinstall#21]
I'm new to github and how it works but I love the project!

I have tried to boot win98qi to a very modern hw with 8GB of memory and a 5600g CPU(that's the lowest stick I have), but got a VCACHE error when trying to boot after installation even with safe mode, but apparently adding cregfix.com file to c:\ then it works for once but then stops working after a restart.

I don't know if it's possible or not to have some sort of options to toggle before installation like limiting the max ram to only use 512mb...etc

Thanks!

**Comment by oerg866** [comment]
Hi,

Unfortunately adding CREGFIX to the installation is not a safe thing to do because older CPUs which lack these registers or have them unwritable will crash when running it.

There is no elegant solution to this problem so I suggest at this moment that you install it by hand and run it in your AUTOEXEC.BAT.

**Comment by oerg866** [comment]
I have added cregfix to the reference ISOs extras folder so the user can install it without hassle

**Comment by Glinckey** [comment]
yippee

**Comment by oerg866** [comment]
Oh hi SweetLow, love your patch work!!

Your VXD version is of course the variant to use there!

**Comment by LordOfMice** [comment]
> or with loaded PM thing like emm386.exe?

JFYI, I made the new variants (.SYS and DPMI)

> love your patch work

Patches are good thing, but the real pushing of limits is new drivers!

P.S. Feel free to use any of my works (and ask me if you will have some problem).

**Comment by oerg866** [comment]
Thank you very much, I appreciate it ♥
