### ISSUE TITLE
LBA Partitions get corrupt after 8GB storage used

### ISSUE THREAD

**Issue by orcutt989** [oerg866/win98-quickinstall#22]
Using about 8GB of any (large) partition of a disk not partitioned with the bigger drive support FDISK makes the volume unbootable and corrupt. Happens on real hardware and 86 box.
See https://www.vogons.org/viewtopic.php?t=84036

Discovered in
https://github.com/86Box/86Box/issues/5044

Integrate newer FDISK into win98 instead of CFDISK
https://archive.org/details/windows-98-and-se-large-drive-fixes.-7z

**Comment by orcutt989** [comment]
I was not able to reproduce this on hardware so I am going back to the 86box team.

**Comment by oerg866** [comment]
Thanks for checking on real hardware. I agree 86box is flaky and I also made the mistake of taking errors it produced seriously before :D

**Comment by orcutt989** [comment]
@oerg866 We spent some time experimenting in that 86Box issue and I came to the conclusion it does have something to do with win98-quickisntall. OEM install works fine with 127GB disk on 86box, but something about windows98-quickinstall corrupts the volume after 8GB written.

**Comment by oerg866** [comment]
Well I'm not sure what to do with this if it doesn't happen on real
hardware...?

**Comment by orcutt989** [comment]
Well by “real hardware” I just meant some random stuff I had setup. Nothing mimicking the motherboard used in 86box. If you look at the linked issue the 86box dev confirmed its an OS issue.

**Comment by OBattler** [comment]
Hello, 86Box lead developer here,

I have indeed determined it to be caused by the OS - it wraps around at 8 GB back to 0, *relative to the first sector of the partition*, because the MBR is still there and hasn't been touched. If this was 86Box itself wrapping around, then it would be have wrapped around absolute 8 GB back to sector 0, which is the MBR, so the MBR would have also been overwritten.

In addition, the Vogons thread shows that it does occur on at least some real PC's as well, and I found a discussion on Reddit suggesting it may be a BIOS-specific issue. In any case, newer FDISK should probably be integrated.

**Comment by oerg866** [comment]
Hello,

I was able to reproduce with 86box and VirtualBox:
![image](https://github.com/user-attachments/assets/218b7f2b-c7f0-40e4-98c9-1b938183c281)
![image](https://github.com/user-attachments/assets/80b63028-f51d-4c44-ba97-f7958a1fb2b7)

Will investigate later after work

**Comment by OBattler** [comment]
I suspect the drivers just assume the drive support 48-bit LBA without actually checking if it does, potentially causing misbehavior on drives that don't support it.

**Comment by oerg866** [comment]
Also regarding FDISK, the newest versions of FDISK and such are already integrated into the reference images

**Comment by orcutt989** [comment]
> Also regarding FDISK, the newest versions of FDISK and such are already integrated into the reference images

Yeah makes sense I think CFDISK is modern enough to handle it. I think @OBattler might be close. Perhaps the RLOEW LBA patch shouldnt be installed if the partition doesnt need it?

**Comment by oerg866** [comment]
It turns out a belarusian user named SweetLow created a patch for R.Loew's ESDI_506.pdr that fixes exactly this problem. After putting it in place, I no longer get errors when writing obscene amounts of content to the drive. This will be fixed in the 0.9.6 reference images

**Comment by oerg866** [comment]
![image](https://github.com/user-attachments/assets/34894fae-c76a-498d-9f7e-c6c0d5fa3c42)

**Comment by orcutt989** [comment]
Amazing!

**Comment by orcutt989** [comment]
> It turns out a belarusian user named SweetLow created a patch for R.Loew's ESDI_506.pdr that fixes exactly this problem. After putting it in place, I no longer get errors when writing obscene amounts of content to the drive. This will be fixed in the 0.9.6 reference images

Why does this work fine on hardware with SATA hard drive and 0.9.5 windows quick install?

**Comment by OBattler** [comment]
Your SATA hard drive more likely than not, supports 48-bit LBA, while 86Box does not and I have no idea about VirtualBox.

**Comment by OBattler** [comment]
If what I read here is true: https://msfn.org/board/topic/186313-patches-for-esdi_506pdr-from-windows-98se-rloews-terabyte-plus-pack-21-and-more/ - then 86Box and VirtualBox somehow both report supporting 48-bit LBA even though they does not.

**Comment by OBattler** [comment]
OK, I just check the 86Box code and we do not report 48-bit LBA as supported in IDENTIFY.

**Comment by OBattler** [comment]
This is getting even more strange - none of the 48-bit LBA commands share their instructions with the 28-bit ones, so RLoew's patch must have a bug where it writes 48-bit LBA parameters even when using a 28-bit LBA command.

**Comment by oerg866** [comment]
Yes, that is also my understanding... Weird stuff.

**Comment by oerg866** [comment]
0.9.6 releases later today, which fixes this

**Comment by LordOfMice** [comment]
> RLoew's patch must have a bug where it writes 48-bit LBA parameters even when using a 28-bit LBA command

RLoew's patch does not have any bug in this area. The bug is in hardware which reports LBA48 support in IDENTIFY DEVICE data but has some bug in handling real LBA48 commands.

But there is enough OTHER bugs (it is not the bugs on old hardware but turned to bugs on modern) in procedure of parameter harmonization of real mode Int 13h handler and ESDI_506.PDR

And yes, I recommend to take the newer version of ESDI_506.PDR as I incorporated other big fix recently (for old problem of RLoew's SATA Patch).

**Comment by OBattler** [comment]
IDE devices on 86Box do not report LBA48 support in IDENTIF DEVICE, at all, so why does the patch still attempt to use 48-bit LBA commands? Furthermore, as I wrote above - 48-bit LBA commands have different opcodes from the 28-bit ones, the driver is sending the latter but writing 48-bit parameters. That does not work correctly on 86Box, whose drives are 28-bit only.

**Comment by LordOfMice** [comment]
OBattler, tell me please:
1. What is the version of ESDI_506.PDR you try to discuss?
2. What your software will do if driver uses CHS access instead of LBA on the standard CHS scheme 16383:16:63 and the cylinder will be above 16383?

**Comment by oerg866** [comment]
Hi, the old versions of the QuickInstall ISOs used the ESDI_506.PDR 24804 bytes (‎Sunday, ‎25 ‎October ‎2015, ‏‎18:49:26 - Not sure if that is the original date) from the R. Loew 1TBPLUS package (attached)

[ESDI_506.zip](https://github.com/user-attachments/files/19634177/ESDI_506.zip)

The new fixed one uses your fixed ESDI_506.PDR (24430 bytes).

**Comment by LordOfMice** [comment]
ESDI_506.PDR 24804 bytes (‎Sunday, ‎25 ‎October ‎2015, ‏‎18:49:26 - Not sure if that is the original date)
A-ha, this is TBP3.0 version! 48-bit LBA + PARTIAL "SATA" Patch (unlike TBP2.1 with FULL "SATA" Patch).
Very dangerous version on modern systems as it has unstable behaviour.
Look to my first post where is the REAL problem of this version.
And there is more complete description (use translator):
https://forum.ru-board.com/topic.cgi?forum=62&topic=31624&start=540#17
Partially note the decsription of cases of wrong detection of LBA & CHS using...

**Comment by oerg866** [comment]
Ahhhhh that explains a *lot* of weird things now. Thank you! 😄

**Comment by LordOfMice** [comment]
Note that I did all planned (on the date of post) enhancements already (and some other too) and I hope that it is ENOUGH.

**Comment by OBattler** [comment]
> What your software will do if driver uses CHS access instead of LBA on the standard CHS scheme 16383:16:63 and the cylinder will be above 16383?

I don't think I do any sanity checks on the cylinder other than erroring out of (C * H * S) is above the last sector of the disk. Otherwise, I treat the cylinder as a standard unsigned 16-bit integer.

Now, from what I recall with the specific problem reported here, as I posted above:

> I have indeed determined it to be caused by the OS - it wraps around at 8 GB back to 0, relative to the first sector of the partition, because the MBR is still there and hasn't been touched. If this was 86Box itself wrapping around, then it would be have wrapped around absolute 8 GB back to sector 0, which is the MBR, so the MBR would have also been overwritten.

8 GB means sector 16777216, this kind of wraparound indicates it's writing the lower 24 bits of LBA correctly (or perhaps even they get overwritten) but then fails to write the upper 4 bits - the only way I can imagine this happening is the driver attempting to use 48-bit LBA with 28-bit read/write commands.

Now the the CHS - 86Box itself, as I said above, in the code, supports a maximum cylinder of 65535. This means it supports a maximum of 65536 * 16 * 256 sectors = 128 MiB, which corresponds to the 28-bit LBA upper limit.

**Comment by LordOfMice** [comment]
Ok, I can say more with internal driver state dumps.
oerg866, can you reproduce error configuration now (with esdi_506.pdr from TBP3.0)?
If so:
http://sweetlow.orgfree.com/download/esdi_506_dump.zip
run go_rl.bat and send me results.

>8 GB means sector 16777216
"8 GB" means 16383:16:63 too if you will calculate as we do not know EXACT wrap-around value,

>65536 * 16 * 256
256 sectors per track config is not usual. 63 SPT and 32GiB limit for CHS are more common values. But yes, 32 GiB are NOT 8 GiB.

**Comment by OBattler** [comment]
We know the exact wrap-around value, it's at sector (16777216 + offset of the first partition), per my analysis of the corrupted hard disk image file, so exactly 8 GiB into the partition, it wraps aroud back to the beginning of the partition. This can only happen if the upper 4 bits of the LBA are never written.

**Comment by LordOfMice** [comment]
> + offset of the first partition

what? there is no parttitions on the level of port drivers...

**Comment by OBattler** [comment]
My analysis of the corrupted hard disk image doesn't lie - the MBR is completely untouched, the overwrite starts at the first sector of the partition,

**Comment by OBattler** [comment]
> > * offset of the first partition
> 
> what? there is no parttitions on the level of port drivers...

And noone is saying there are - the wraparound occurs when Windows is attempting to access sector (first sector of the partition + 16777216) but, for whatever reason, does not write the upper 4 its, causing the very beginning of the partition to be written to instead.

**Comment by LordOfMice** [comment]
>Windows then tries to access sector 0x01000500
BEFORE this Windows had to access 0x1000000...

**Comment by oerg866** [comment]
Hello, im sorry I am too busy at the moment but in 0.9.6 for sure the bug
is gone because it uses SweetLow's patched files and I could not reproduce
the problem there anymore :)

**Comment by LordOfMice** [comment]
> I could not reproduce the problem there anymore

As I said - try to take TBP3.0 ESDI_506.PDR instead of my version (and copy it to %windir%\SYSTEM\IOSUBSYS)

>im sorry I am too busy at the moment 

We're in no hurry ;)

>At this point, I have no idea what exactly is going on, anymore.

That's why I want to insulate it consistently. But it has to be reproduced for the first step, of course.

**Comment by oerg866** [comment]
Ahhh, I understand now. Will do tomorrow or wednesday

**Comment by OBattler** [comment]
That's in VirtualBox, I'm not sure how that affects 86Box which is entirely separate.

**Comment by OBattler** [comment]
Every ATA specification I can find, lists bit 3 as reserved, and ATA-1 outright lists it as always being set.

**Comment by LordOfMice** [comment]
>Every ATA specification I can find, lists bit 3 as reserved, and ATA-1 outright lists it as always being set.

Because it is pre ATA and even pre IDE. It is WD1003 & ST506 era.

>That's in VirtualBox, I'm not sure how that affects 86Box which is entirely separate.

I thought that is the same problem:
oerg866: >I was able to reproduce with 86box **and** VirtualBox

Ok, @oerg866 tell me please what the software you are using for tests and can it be retested for the second one?

**Comment by OBattler** [comment]
I'm trying to locate any pre-ATA/pre-IDE specification to see what that bit meant but I've so far had no luck.

> oerg866: >I was able to reproduce with 86box and VirtualBox

Likely for a bit different reasons - 86Box does not emulate 48-bit LBA atall and I think the driver assumes a 48-bit capable drive, which is going to result in erroneous behavior on 86Box (and on any real non-48-bit-capable drive). But someone needs to do logging with 86Box to see what's actually going on.

**Comment by LordOfMice** [comment]
>I'm trying to locate any pre-ATA/pre-IDE specification to see what that bit meant but I've so far had no luck.

1. It means that 8+ heads drive is installed.
2. The Undocumented PC by Frank van Gilluwe  - any edition.

>But someone needs to do logging with 86Box to see what's actually going on.

True.

**Comment by oerg866** [comment]
> > Every ATA specification I can find, lists bit 3 as reserved, and ATA-1 outright lists it as always being set.
> 
> Because it is pre ATA and even pre IDE. It is WD1003 & ST506 era.
> 
> > That's in VirtualBox, I'm not sure how that affects 86Box which is entirely separate.
> 
> I thought that is the same problem: oerg866: >I was able to reproduce with 86box **and** VirtualBox
> 
> Ok, [@oerg866](https://github.com/oerg866) tell me please what the software you are using for tests and can it be retested for the second one?

I was using VirtualBox, but I can retest on 86box next week

**Comment by OBattler** [comment]
Reading the Russian forum post linked above (thankfully, I understand Russian), it seems as if RLoew's patch doesn't even attempt to detect what kind of drive is in use and just assumes LBA.

Now, if I'm correct (but I have to log to confirm that), it appears to assume a 48-bit LBA IDE task file as opposed to a 28-bit one - that is, no top 4 bits in the drive/head register and instead, a second write to the task file writes the bottom 24 bits and the first write writes the top 24 bits. Now, 28-bit LBA read and write commands even on a 48-bit drive still use the task file the old fashioned way, so if RLoew's patch really causes task file writes to assume 48-bit operation even with 28-bit command, that would perfectly explain why the observed problem happens.

But logging should tell us more about what actually happens.

**Comment by LordOfMice** [comment]
> it seems as if RLoew's patch doesn't even attempt to detect what kind of drive is in use and just assumes LBA

1. In TBP 2.1 or in SATA patch.
2. TBP 3.0 has usual detection of mode in which BIOS is accessing drive - and we checked exactly THIS version.
3. And I assume your ATA emulation propagates LBA mode :)

>if RLoew's patch really causes task file writes to assume 48-bit operation even with 28-bit command

No, it is not. As I wrote it uses 48-bit LBA command on drives of ANY size if those drives report support of such commands unlike LLXX's patch, Windows NT or my patch but this is NOT problem on CORRECT hardware or emulation.

**Comment by OBattler** [comment]
86Box does not report support of such commands, at all, so there's no way the patch could possibly think it does.

And yes, my ATA emulation, for bigger drives, does report LBA, yes. But not the 48-bit LBA commands. So the driver, by all logic, should be using 28-bit LBA commands with 28-bit LBA addresses. But that would not explain the wraparound observed. Neither does your hypothesis of it attempting to use 48-bit *commands* - those would abort as illegal on 86Box and therefore, not overwrite anything.

**Comment by LordOfMice** [comment]
@oerg866 , @OBattler 
RLoew's TBP3.0 ESDI_506.PDR bug confirmed - exactly LBA28 only drives wrap-around to LBA24 (and code is slower than needed). LBA48 drives work as expected. Fix:
http://sweetlow.orgfree.com/download/esdi_506_tbp3.zip

**Comment by oerg866** [comment]
@LordOfMice Thanks for sharing!

Does this change anything about which PDR file to include in the images? Or should I stay with your 2.1 version?

Thanks! :) 

PS: I can't reply to your e-mail, it says the domain cannot be resolved :(

**Comment by LordOfMice** [comment]
>Does this change anything about which PDR file to include in the images?

No. I just did this one and only fix for TBP3.0 because it is pretty hard bug (and to verify that I correctly insulated problem too) and I sometimes use this version for tests. And no other patches applied.

>Or should I stay with your 2.1 version?

Yes.

> I can't reply to your e-mail, it says the domain cannot be resolved :(

Ok, I will send answer from other mail.

**Comment by LordOfMice** [comment]
And the last but not least.

>>>>We know the exact wrap-around value, it's at sector (16777216 + offset of the first partition), per my analysis of the corrupted hard disk image file, so exactly 8 GiB into the partition, it wraps aroud back to the beginning of the partition. 

>>>Windows then tries to access sector 0x01000500

>>BEFORE this Windows had to access 0x1000000...

>Yes, now that you point this out, it's indeed puzzling why that doesn't wrap around.

My golden rule confirmed once again - there is no such thing as unimportant error in system code.
@OBattler  IDK what is the source of problem you studied, but I reproduced this "protected area @ LBA 0" situation. And explanation  is simple - when you write large size packed (say 32K @ 16777216 - 16) it will be successfully positioned on the right place (wrap-around is inside software, NOT hardware), but the next packet (32K @ 48) will skip MBR but overwrite begin of the first partition.

**Comment by OBattler** [comment]
Wouldn't the next packet be at 32K @ 16 (ie. 32 K @ 16777216 + 16 = 32 K @ 16777216 - 16 + 32, with only the low 24 bits preserved)? In which case, yes. The next write would be at 16777216 + 16 but with only the low 24 bits preserved, it would go to 16 instead, skipping the MBR but overwriting the first partition. This matches my observation.

This happens because of a bug in RLoew's patch - it assumes 48-bit LBA even when 28-bit LBA commands are used, so it will first write the upper 24 bits, then the lower 24 bits to the same registers, while leaving the upper 4 bits in the head register used by the 28-bit commands unchanged at 0. This will cause the 28-bit LBA command to write to the wrong address. Perhaps I should do some logging of this one of these days just to make sure.

**Comment by OBattler** [comment]
Unless the patch is not wrong for 28-bit LBA on a 48-bit drive and the lower 4 bits of the upper 48 bits are mirrored into the head register. I need to read the ATA spec again for that.

**Comment by OBattler** [comment]
The specification is unclear but assuming the registers write to an internal LBA address register, then this would make sense. If this is true, then RLoew's patch is fine, it just assumes a drive is 48-bit LBA *capable* even if its size fits within 28 bits. This would mean that it broke on 86Box because 86Box emulates an earlier ATA specfication where 48-bit LBA did not even exist at all and therefore, RLoew's patch was never intended to be compatible with to begin with.
