### ISSUE TITLE
Doesn't boot on original hardware.

### ISSUE THREAD

**Issue by andreacampanella** [oerg866/win98-quickinstall#5]
I'm trying to boot this on my pentium 266mhz, the CDROM doesn't seem to work and if I use PCem and transfer the image the bootloader complaing about a division error, is this supposed to be compatible with old architectures?

**Comment by oerg866** [comment]
Hi, yes this is designed for and tested with old architectures. I just tested it on a 486DX.

Can you post steps to reproduce and some screenshots?

**Comment by andreacampanella** [comment]
Seems like my board has a problem, sorry for the ticket

**Comment by oerg866** [comment]
No worries! Thanks for testing :) feel free to open a new ticket if new problems come up!
